---
deployment:
  tasks:
    - export DEPLOYPATH=/home/${USER}/public_html/
    - echo "Starting deployment to $DEPLOYPATH"
    - /bin/rm -rf ${DEPLOYPATH}/*
    - /bin/cp -R * ${DEPLOYPATH}
    - echo "Deployment completed successfully!"
